/*
 * Generated by src/saveVersion.sh
 */
@VersionAnnotation(version="0.2.4", revision="8074e6099f11849ec69e4fe7eb9902a011d35a3b",
                         user="liushaohui", date="Thu Aug 21 22:00:50 CST 2014", url="git://liushaohui-OptiPlex-990/home/liushaohui/workspace/private/rockstor/server")
package com.rockstor;
